public class FFJWTClaims {
    public String environment {get;set;}
    public String environmentIdentifier {get;set;}
    public String project {get;set;}
    public String projectIdentifier {get;set;}
    public String accountID {get;set;}
    public String organization {get;set;}
    public String organizationIdentifier {get;set;}
    public String clusterIdentifier {get;set;}
    public String key_type {get;set;}
}
